version: '4.2'

services:
  source_postgres:
    image: postgres:16
    ports:
      - '5433:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  destination_postgres:
    image: postgres:16
    ports:
      - '5434:5432'
    networks:
      - elt_network
