version: '4.2'

services:
  source_postgres:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - source_data:/var/lib/postgresql/data
      - ./source/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elt_network

  destination_postgres:
    image: postgres:16
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - destination_data:/var/lib/postgresql/data
    networks:
      - elt_network

  elt_script:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python', 'main.py']
    depends_on:
      - source_postgres
      - destination_postgres
    networks:
      - elt_network

networks:
  elt_network:
    driver: bridge

volumes:
  source_data:
  destination_data:
